# Generated by Django 5.1.3 on 2024-11-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_question_question_type_wordanswer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WordAnswer",
        ),
    ]
