# Generated by Django 5.1.3 on 2024-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_quizattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="user",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="answers",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.FloatField(null=True),
        ),
    ]
